name: medify
description: "Medicine Reminder & Tracker App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Local Database
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0

  # Dependency Injection
  get_it: ^8.0.3

  # Local Notifications
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0
  permission_handler: ^12.0.1

  # Utilities
  intl: ^0.20.1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.3.3

  # Charts & Visualizations (Phase 2)
  fl_chart: ^0.69.0

  # Calendar & History (Phase 2)
  table_calendar: ^3.1.2
  csv: ^6.0.0
  share_plus: ^10.1.2

  # UI Enhancements (Phase 2)
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ObjectBox code generation
  build_runner: ^2.4.14
  objectbox_generator: ^5.0.0

  # Native splash screen generation
  flutter_native_splash: ^2.4.3

  # Launcher icon generation
  flutter_launcher_icons: ^0.14.1

  # Asset code generation
  flutter_gen_runner: ^5.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/songs/

  # Fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800

# Flutter Native Splash Configuration
flutter_native_splash:
  # Logo image (using main logo)
  image: assets/images/Medify.png

  # Background color (using Medify's light background color)
  color: "#FAFAFA"

  # Dark mode configuration
  color_dark: "#111827"
  image_dark: assets/images/Medify.png

  # Android 12+ specific settings
  android_12:
    image: assets/images/Medify.png
    color: "#FAFAFA"
    image_dark: assets/images/Medify.png
    color_dark: "#111827"

  # Web configuration (optional)
  web: false

  # iOS configuration
  ios: true
  android: true

  # Branding mode (keeps splash visible until app is ready)
  android_gravity: center
  ios_content_mode: center

  # Full screen (recommended for splash screens)
  fullscreen: true

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Medify.png"
  adaptive_icon_background: "#FAFAFA"
  adaptive_icon_foreground: "assets/images/Medify.png"
  # Remove default Flutter icon
  remove_alpha_ios: true

# Flutter Gen Configuration for type-safe asset access
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: false
  assets:
    enabled: true
