name: medify
description: "Medicine Reminder & Tracker App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Local Database
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0

  # Dependency Injection
  get_it: ^8.0.3

  # Local Notifications
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0
  permission_handler: ^12.0.1

  # Utilities
  intl: ^0.20.1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ObjectBox code generation
  build_runner: ^2.4.14
  objectbox_generator: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
